-- PrintFlow: esquema inicial para Supabase
create table if not exists public.print_jobs (
  id text primary key,
  filename text not null,
  storage_path text not null,
  copies integer not null default 1 check (copies between 1 and 99),
  status text not null default 'PENDING' check (status in ('PENDING','PRINTING','COMPLETED','FAILED','CANCELLED')),
  error_message text,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create index if not exists print_jobs_status_created_idx on public.print_jobs(status, created_at desc);

-- Para el MVP personal, el backend usa la service role key y no expone esta tabla al navegador.
alter table public.print_jobs enable row level security;

create table if not exists public.printer_settings (
  id integer primary key default 1 check (id = 1),
  name text not null default 'EPSON L4150 Series',
  paper text not null default 'A4',
  color_mode text not null default 'COLOR' check (color_mode in ('COLOR','GRAYSCALE')),
  quality text not null default 'NORMAL' check (quality in ('DRAFT','NORMAL','HIGH')),
  default_copies integer not null default 1 check (default_copies between 1 and 99),
  active boolean not null default true,
  updated_at timestamptz not null default now()
);
insert into public.printer_settings (id) values (1) on conflict (id) do nothing;
alter table public.printer_settings enable row level security;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  event text not null,
  job_id text,
  details jsonb,
  created_at timestamptz not null default now()
);
create index if not exists activity_logs_created_idx on public.activity_logs(created_at desc);
alter table public.activity_logs enable row level security;
