import fs from 'node:fs';
import path from 'node:path';
import {execFile} from 'node:child_process';
const base=process.env.PRINTFLOW_URL||'http://localhost:3000', configuredPrinter=process.env.PRINTER_NAME||'Epson L4150', temp=process.env.TEMP||'.', sumatra=process.env.SUMATRA_PATH||'C:\\Users\\HOME\\AppData\\Local\\SumatraPDF\\SumatraPDF.exe'; let printer=configuredPrinter, printSettings={paper:'A4',color_mode:'COLOR',quality:'NORMAL'};
const activeJobs=new Set();
const logDir=path.join(process.env.LOCALAPPDATA||process.cwd(),'PrintFlow','logs');fs.mkdirSync(logDir,{recursive:true});const logFile=path.join(logDir,'agent.log');
function log(message){const line=`${new Date().toISOString()} ${message}`;console.log(line);fs.appendFileSync(logFile,line+'\n')}
log('Agent iniciado. Impresora: '+printer); poll(); setInterval(poll,3000);
async function poll(){try{const settings=await fetch(base+'/api/settings/printer');if(settings.ok){const s=await settings.json();if(s.active&&s.name){printer=s.name;printSettings=s}}if(!(await printerReady()))throw Error('Impresora no disponible: '+printer);const r=await fetch(base+'/api/jobs');if(!r.ok)throw Error('API '+r.status);const jobs=await r.json();const job=jobs.find(j=>j.status==='PENDING'&&!activeJobs.has(j.id));if(job)await print(job)}catch(e){log('POLL ERROR: '+e.message)}}
async function printerReady(){return new Promise(resolve=>execFile('powershell.exe',['-NoProfile','-Command',`$p=Get-Printer -Name '${printer.replaceAll("'","''")}' -ErrorAction SilentlyContinue; if($p -and !$p.WorkOffline){'true'}else{'false'}`],(e,stdout)=>resolve(!e&&stdout.trim()==='true')))}
async function print(job){if(activeJobs.has(job.id))return; activeJobs.add(job.id); const out=path.join(temp,job.id+'.pdf'); try{log('Iniciando '+job.id);await status(job.id,'PRINTING');const r=await retryFetch(base+'/api/jobs/'+job.id+'/file',3);if(!r.ok)throw Error('No se pudo descargar el PDF ('+r.status+')');fs.writeFileSync(out,Buffer.from(await r.arrayBuffer()));await retry(()=>printWithEdge(out,job.copies),3);await status(job.id,'COMPLETED');log('Completado '+job.id)}catch(e){log('ERROR '+job.id+': '+e.message);await status(job.id,'FAILED',e.message)}finally{if(fs.existsSync(out))fs.unlinkSync(out);activeJobs.delete(job.id)}}
async function applyPrinterConfig(){const color=printSettings.color_mode!=='GRAYSCALE';const paper=['A4','A5','Letter'].includes(printSettings.paper)?printSettings.paper:'A4';await new Promise((resolve,reject)=>execFile('powershell.exe',['-NoProfile','-Command',`Set-PrintConfiguration -PrinterName '${printer.replaceAll("'","''")}' -Color $${color?'true':'false'} -PaperSize '${paper}'`],e=>e?reject(e):resolve()));log(`Configuración aplicada: papel=${paper}, color=${color?'COLOR':'GRAYSCALE'}, calidad=${printSettings.quality} (calidad depende del driver Epson)`)}
function retry(fn,times){return fn().catch(e=>times>1?new Promise(r=>setTimeout(r,2000)).then(()=>retry(fn,times-1)):Promise.reject(e))}async function retryFetch(url,times){try{return await fetch(url)}catch(e){if(times<=1)throw e;await new Promise(r=>setTimeout(r,2000));return retryFetch(url,times-1)}}
function printWithEdge(file,copies=1){if(!fs.existsSync(sumatra))return Promise.reject(Error('No se encontró SumatraPDF en '+sumatra));return new Promise((resolve,reject)=>{let left=Number(copies)||1;const next=()=>{if(left--<=0)return resolve();execFile(sumatra,['-print-to',printer,'-silent',file],(err)=>err?reject(err):setTimeout(next,1500))};next()})}
async function status(id,s,errorMessage){await fetch(base+'/api/agent/jobs/'+id+'/status',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status:s,errorMessage})})}
